apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: dummy
    app.kubernetes.io/component: dummy
    app.kubernetes.io/instance: dummy
    app.kubernetes.io/part-of: poc
    app.kubernetes.io/name: java
  name: dummy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    app: dummy
    deploymentconfig: dummy
    version: v1
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: dummy 
        deploymentconfig: dummy
        version: v1
    spec:
      containers:
      - image: quay.io/voravitl/backend-native:v1
        imagePullPolicy: IfNotPresent
        name: dummy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  # - imageChangeParams:
  #     automatic: true
  #     containerNames:
  #     - dummy
  #     from:
  #       kind: ImageStreamTag
  #       name: dummy-native:v1
  #       namespace: demo
  #   type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
