apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: frontend-v2
    app.kubernetes.io/component: frontend-v2
    app.kubernetes.io/instance: frontend-v2
    app.kubernetes.io/part-of: poc
    app.kubernetes.io/name: nodejs
  name: frontend-v2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    app: frontend-v2
    deploymentconfig: frontend-v2
    version: v1
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: frontend-v2 
        deploymentconfig: frontend-v2
        version: v1
    spec:
      containers:
      - image: quay.io/voravitl/frontend-js:v2
        imagePullPolicy: IfNotPresent
        name: frontend-v2
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: BACKEND_URL
            value: http://backend.namespace-2.svc.cluster.local:8080
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  # - imageChangeParams:
  #     automatic: true
  #     containerNames:
  #     - frontend-v2
  #     from:
  #       kind: ImageStreamTag
  #       name: frontend-v2-native:v1
  #       namespace: demo
  #   type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
