apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/part-of: poc
    app.kubernetes.io/name: nodejs
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    app: frontend
    deploymentconfig: frontend
    version: v1
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: frontend 
        deploymentconfig: frontend
        version: v1
    spec:
      containers:
      - image: quay.io/voravitl/frontend-js:v1
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: BACKEND_URL
            value: http://backend.namespace-2.svc.cluster.local:8080
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /satus
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /satus
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  # - imageChangeParams:
  #     automatic: true
  #     containerNames:
  #     - frontend
  #     from:
  #       kind: ImageStreamTag
  #       name: frontend-native:v1
  #       namespace: demo
  #   type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
