apiVersion: v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 5500ms
    #haproxy.router.openshift.io/ip_whitelist:
    haproxy.router.openshift.io/rate-limit-connections: true
    haproxy.router.openshift.io/rate-limit-connections.rate-http: 5
