apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels:
    k8s-app: app-monitor
spec:
  namespaceSelector:
    matchNames:
      - namespace-2
  selector:
    matchLabels:
      app: backend
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
